version: '2.1'
services:

  backend:
    image: ngroyal/github-workflow-dashboard-backend:main
    container_name: backend
    ports:
      - 3100:3100
    environment:
      - ORG_NAME=
      - ACCESS_TOKEN=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ngroyal/github-workflow-dashboard-frontend:main
    container_name: frontend
    ports:
      - 3000:3000

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github
    volumes:
      - ./pgdata:/var/lib/postgresql/data
