version: '2'
services:

  backend:
    build: ../backend
    container_name: backend-container
    ports:
      - 3100:3100
    environment:
      - ORG_NAME=
      - ACCESS_TOKEN=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ../frontend
    container_name: frontend-container
    ports:
      - 3000:3000
    environment:
      - BACKEND_BASE_URL=http://host.docker.internal:3100

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github
    volumes:
      - ./pgdata:/var/lib/postgresql/data
