name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.dockerhub_user }}
        password: ${{ secrets.dockerhub_token }}
        
    # Test build in PR
    # create tags
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ngroyal/github-workflow-dashboard
  
    # build images 
    - name: Build backend
      id: build-backend
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: backend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: backend-${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
    - name: Build frontend
      id: build-frontend
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        file: frontend/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: frontend-${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
# TODO: only build frontend/backend if files changed for one of them respectively
