name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        registry: hub.docker.com
        username: ${{ DOCKERHUB_USER }}
        password: ${{ DOCKERHUB_TOKEN }}
    # Test build in PR
    - name: Build backend
      if: ${{ github.event_name == 'pull_request' }}
      id: build-latest-backend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: backend/Dockerfile
        push: false
        tags: github-workflow-dashboard:backend-$(date +%s)
  
    - name: Build frontend
      if: ${{ github.event_name == 'pull_request' }}
      id: build-latest-frontend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: frontend/Dockerfile
        push: false
        tags: github-workflow-dashboard:frontend-$(date +%s)
